window.productData = {
    "p1": {
        name: "P47 Wireless Headphone",
        price: "৳ 250",
        image: "/images/p1.avif",
        url: "product.html?id=p1",   
        category: "Electronics",
        delivery: "3-5 Business Days",
        warranty: "6 Months Seller Warranty",
        details: [
            "This versatile Bluetooth headphone offers crystal-clear audio quality and ergonomic design for extended comfort.",
            "Type: Wireless Bluetooth Headphone"
        ],
        specs: ["Material: ABS Plastic", "Weight: 0.3kg", "Connectivity: Bluetooth 5.0"],
        color: ["Black", "Blue", "Red"],
    },
    "p2": {
        name: "Lotto Comfortable Slide",
        price: "৳ 570",
        image: "/images/p2.avif",
        url: "product.html?id=p2",       
        category: "Fashion",
        delivery: "3-5 Business Days",
        warranty: "30-day Replacement",
        details: ["Perfect for casual, everyday use."],
        specs: ["Material: Rubber", "Waterproof", "Lightweight"],
        color: ["Black", "Green"],
    },
    "p3": {
        name: "Smart TV Box",
        price: "৳ 2250",
        image: "/images/p3.avif",
        url: "product.html?id=p3",  
        category: "Electronics",
        delivery: "3-5 Business Days",
        warranty: "1 Year Service",
        details: ["Transform your TV into a smart media center."],
        specs: ["OS: Android 10", "RAM: 4GB"],
        color: ["Black"],
    },
    "p4": {
        name: "Waist Travel Purse",
        price: "৳ 330",
        image: "/images/p4.avif",
        url: "product.html?id=p4",    
        category: "Fashion",
        warranty: "None",
        details: ["Secure and lightweight purse for travel essentials."],
        specs: ["Material: Nylon", "Water resistant"],
        color: ["Gray", "Blue"],
    },
    "p5": {
        name: "Realme C71 6GB/128GB",
        price: "৳ 15550",
        image: "/images/p5.avif",
        url: "product.html?id=p5",     
        category: "Electronics",
        warranty: "1 Year Official",
        details: ["High-performance smartphone with great battery life."],
        specs: ["Display: 6.5\"", "Camera: 48MP"],
        color: ["Black", "White"],
    },
    "p6": {
        name: "M8 GameBox",
        price: "৳ 1779",
        image: "/images/p6.avif",
        url: "product.html?id=p6",        
        category: "Electronics",
        warranty: "6 Months",
        details: ["Retro gaming console with hundreds of games."],
        specs: ["Resolution: 4K", "Includes 2 controllers"],
        color: ["Gray"],
    },
    "p7": {
        name: "Baby Winter Jumpsuit With Hood",
        price: "৳ 590",
        image: "/images/p7.avif",
        url: "product.html?id=p7",        
        category: "Fashion",
        warranty: "None",
        details: ["Warm and cozy jumpsuit for babies."],
        specs: ["Material: Fleece", "Sizes: 0-12M"],
        color: ["Pink", "Blue"],
    }
};
